# Publish docs to gh-pages and release package on PyPi

name: Deploy docs and package

on:
  push:
    tags:
    - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y pandoc # for markdown notebook cells
        python -m  pip install --upgrade pip
        pip install flake8 pytest
        pip install .   # install package with requirements
        pip install -r requirements-dev.txt
        pip install setuptools wheel twine
        python -m ipykernel install --user
    - name: Build sphinx documentation
      run: |
        sudo rm -f ./docs/source/outputs/*.xlsx
        sudo rm -f ./docs/source/outputs/*peakshape_calib.txt
        make -C docs clean   # clear build directory
        set -e   # exit if building docs fails
        make -C docs html
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Publish docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          destination_dir: ${{steps.tag.outputs.tag}}
    - name: Update gh-pages index
      uses: actions/checkout@v2
        with:
          ref: gh-pages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./make-index.sh
        git add -f .
        git commit --allow-empty -m "Update gh-pages index with new tagged version."
        git push -fq origin gh-pages
      shell: bash
    # - name: Build and release package 
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: |
    #     python setup.py sdist bdist_wheel
    #     twine upload dist/*
